$(function() {

    // Populate using an object literal

    WTF.init({

        heading: [
            "Watch as I fucking roleplay a",
            "Check this out, a fucking",
            "Look at me, I'm going to be a fucking",
            "My character is a fucking"
        ],

        response: [
            "I don't fucking want that one, give me another",
            "Already fucking played one, try something else",
            "Give me a-fucking-nother one",
            "That's a fucking awful combination, try again",
            "That makes no fucking sense, start over",
            "Make a fucking better character"
        ],

        template: [
            "@Adj @Culture @Genotype @Occupation from @Place who @Quirk and @Quirk",
            "@Adj @Culture @Genotype @Occupation from @Place who @Quirk"
        ],

        Adj: [
            "Absent-minded",
            "Adorable",
            "Adventurous",
            "Affable",
            "Agreeable",
            "Aloof",
            "Ambitious",
            "Amiable",
            "Amusing",
            "Ancient",
            "Angry",
            "Apathetic",
            "Arrogant",
            "Articulate",
            "Assertive",
            "Astute",
            "Attentive",
            "Authentic",
            "Balanced",
            "Bashful",
            "Bitchy",
            "Bitter",
            "Blunt",
            "Boisterous",
            "Bold",
            "Brash",
            "Brave",
            "Bright",
            "Brilliant",
            "Calm",
            "Capable",
            "Captivating",
            "Carefree",
            "Careful",
            "Caring",
            "Cautious",
            "Charismatic",
            "Charming",
            "Cheerful",
            "Childish",
            "Chill",
            "Clever",
            "Clumsy",
            "Collaborative",
            "Committed",
            "Compassionate",
            "Condescending",
            "Confident",
            "Conscientious",
            "Considerate",
            "Consistent",
            "Constructive",
            "Contemplative",
            "Content",
            "Cooperative",
            "Courageous",
            "Courteous",
            "Cowardly",
            "Creative",
            "Cultured",
            "Cunning",
            "Curious",
            "Curt",
            "Cynical",
            "Dandy",
            "Dapper",
            "Daring",
            "Decisive",
            "Dedicated",
            "Deep",
            "Defiant",
            "Delightful",
            "Dense",
            "Dependable",
            "Depressed",
            "Determined",
            "Devoted",
            "Dexterous",
            "Diligent",
            "Discerning",
            "Disciplined",
            "Discreet",
            "Disillusioned",
            "Dopey",
            "Dynamic",
            "Eager",
            "Earnest",
            "Easygoing",
            "Eccentric",
            "Effective",
            "Efficient",
            "Eloquent",
            "Emotional",
            "Empathetic",
            "Energetic",
            "Engaging",
            "Enthusiastic",
            "Erratic",
            "Evasive",
            "Exciting",
            "Experienced",
            "Expert",
            "Explorative",
            "Expressive",
            "Extroverted",
            "Exuberant",
            "Fair",
            "Faithful",
            "Fancy",
            "Fat",
            "Fearless",
            "Feisty",
            "Fit",
            "Flamboyant",
            "Fluffy",
            "Focused",
            "Forgiving",
            "Friendly",
            "Frightened",
            "Frugal",
            "Fulfilled",
            "Fun-loving",
            "Gallant",
            "Generous",
            "Gentle",
            "Genuine",
            "Giving",
            "Good-natured",
            "Graceful",
            "Gracious",
            "Greedy",
            "Grouchy",
            "Gruff",
            "Grumpy",
            "Gullible",
            "Happy",
            "Hardworking",
            "Harmonious",
            "Haughty",
            "Helpful",
            "Helpless",
            "Heroic",
            "Honest",
            "Honorable",
            "Hopeful",
            "Humane",
            "Humble",
            "Humorous",
            "Idealistic",
            "Imaginative",
            "Impartial",
            "Impatient",
            "Impulsive",
            "Independent",
            "Industrious",
            "Influential",
            "Ingenious",
            "Innovative",
            "Inquisitive",
            "Insensitive",
            "Insightful",
            "Inspiring",
            "Intelligent",
            "Intense",
            "Intuitive",
            "Inventive",
            "Irrational",
            "Jealous",
            "Jittery",
            "Jolly",
            "Jovial",
            "Joyful",
            "Judgmental",
            "Judicious",
            "Just",
            "Keen",
            "Kind",
            "Kindhearted",
            "Knowledgeable",
            "Lazy",
            "Leaderly",
            "Lethargic",
            "Level-headed",
            "Liberated",
            "Lithe",
            "Lively",
            "Logical",
            "Lonely",
            "Loud",
            "Loving",
            "Loyal",
            "Lucky",
            "Magnetic",
            "Manipulative",
            "Mature",
            "Mean",
            "Measured",
            "Melancholy",
            "Merry",
            "Methodical",
            "Meticulous",
            "Mighty",
            "Mindful",
            "Miserable",
            "Modest",
            "Moody",
            "Morose",
            "Motivated",
            "Mysterious",
            "Narcissistic",
            "Needy",
            "Nervous",
            "Noble",
            "Nosey",
            "Nurturing",
            "Objective",
            "Observant",
            "Obstinate",
            "Old",
            "Old-fashioned",
            "Open-minded",
            "Optimistic",
            "Opulent",
            "Orderly",
            "Organized",
            "Original",
            "Outgoing",
            "Overbearing",
            "Overconfident",
            "Paranoid",
            "Passionate",
            "Patient",
            "Peaceful",
            "Pensive",
            "Perceptive",
            "Persistent",
            "Personable",
            "Persuasive",
            "Pessimistic",
            "Philanthropic",
            "Philosophical",
            "Pioneering",
            "Playful",
            "Pleasent",
            "Plucky",
            "Polite",
            "Pompous",
            "Positive",
            "Powerful",
            "Practical",
            "Precise",
            "Pretentious",
            "Proactive",
            "Productive",
            "Professional",
            "Profound",
            "Progressive",
            "Protective",
            "Punctual",
            "Purposeful",
            "Quick",
            "Quick-witted",
            "Quiet",
            "Racist",
            "Rad",
            "Radiant",
            "Radical",
            "Rational",
            "Realistic",
            "Rebellious",
            "Reckless",
            "Reflective",
            "Relaxed",
            "Reliable",
            "Reluctant",
            "Resourceful",
            "Respectful",
            "Responsible",
            "Responsive",
            "Rude",
            "Sarcastic",
            "Sassy",
            "Savvy",
            "Scholarly",
            "Scrupulous",
            "Secure",
            "Self-assured",
            "Self-directed",
            "Self-disciplined",
            "Selfless",
            "Sensible",
            "Sensitive",
            "Serious",
            "Sexist",
            "Shifty",
            "Short",
            "Short-Tempered",
            "Sincere",
            "Skillful",
            "Skinny",
            "Sleepy",
            "Sloppy",
            "Sly",
            "Snippy",
            "Snobby",
            "Spirited",
            "Spiteful",
            "Spontaneous",
            "Stand-offish",
            "Steadfast",
            "Stoic",
            "Strict",
            "Strong",
            "Sullen",
            "Supportive",
            "Surly",
            "Sympathetic",
            "Talented",
            "Tall",
            "Tenacious",
            "Thoughtful",
            "Tidy",
            "Timid",
            "Tired",
            "Tolerant",
            "Touchy",
            "Tricky",
            "Trustful",
            "Trustworthy",
            "Twitchy",
            "Ugly",
            "Unassuming",
            "Uncoordinated",
            "Understanding",
            "Upbeat",
            "Verbose",
            "Versatile",
            "Vibrant",
            "Vile",
            "Violent",
            "Warmhearted",
            "Wary",
            "Wicked",
            "Wise",
            "Witty",
            "Wordy",
            "Worried",
            "Xenophobic",
            "Young",
            "Zealous",
            "Zippy"
        ],

        Culture: [
            "Commonality",
            "Core Worlds",
            "Neo-Culture",
            "Lost Colony",
            "Rediscovered World"
        ],

        Genotype: [
            "Human",
            "Xenomorph",
            "Synthetic"
        ],

        Occupation: [
            "Civilian",
            "Diplomat",
            "Downtecher",
            "Explorer",
            "Merchant",
            "Military",
            "Rogue",
            "Sci-Tech",
            "Security",
            "Spacer"
        ],

        Place: [
            "a scientific research station",
            "a suburban cul-de-sac",
            "a nomadic tribe",
            "a gritty industrial town",
            "an isolated, mountainous region",
            "a remote, rural island",
            "a small mining town",
            "a refugee settlement",
            "an upper-class gated community",
            "a farming community",
            "a beach town with a strong surfing culture",
            "a dense urban neighborhood",
            "a remote fishing village",
            "a nomadic caravan",
            "an underground bunker community",
            "a space station orbiting a black hole",
            "a planet with six suns",
            "an underwater city on an ocean planet",
            "a colony on a terraformed asteroid",
            "a biodome on a distant moon",
            "a space-faring nomadic tribe",
            "a genetically-engineered human colony",
            "a research station on the edge of the galaxy",
            "a virtual reality world",
            "a planet with a shattered moon in the sky",
            "a rogue planet drifting through space",
            "a city built into the ruins of an ancient alien civilization",
            "an artificial planet designed for luxury living",
            "a massive intergalactic spaceport",
            "a planet with floating islands in the sky",
            "a post-apocalyptic wasteland",
            "a planet with a toxic atmosphere",
            "a spacefaring race of sentient machines",
            "a massive space colony in a Lagrange point",
            "a planet where time flows differently",
            "a planet with a molten core",
            "a mining colony on an asteroid belt",
            "a colony on a planet with a harsh desert climate",
            "a research station orbiting a neutron star",
            "a space station in orbit around a gas giant",
            "a planet with a ring system",
            "a colony on a planet with a sentient plant life",
            "a spaceship that never lands",
            "a planet with a binary star system",
            "an interstellar trading hub",
            "a planet with an artificially-intelligent ecosystem",
            "a colony on a planet with extreme gravitational conditions",
            "a planet with a civilization that communicates through dance",
            "a research station in orbit around a pulsar",
            "a planet with a sentient ocean",
            "a space station powered by a miniature black hole",
            "a colony on a planet with a parasitic species",
            "a planet with a crystalline surface",
            "a nomadic tribe traveling through the galaxy",
            "a space station built from a hollowed-out asteroid",
            "a planet with a civilization that communicates telepathically",
            "a colony on a planet with a highly-toxic biosphere",
            "a planet with a highly radioactive atmosphere",
            "a planet with a sentient cloud-based species",
            "a space station in a debris field",
            "a planet with a highly unstable orbit",
            "a colony on a planet with a non-carbon-based ecosystem",
            "a planet with a highly-magnetic atmosphere",
            "a research station orbiting a quasar",
            "a planet with a single, massive continent",
            "a space station designed for research on dark matter",
            "a colony on a planet with a perpetually dark side",
            "a planet with a sentient crystal species",
            "a spacefaring race of genetically-enhanced humans",
            "a city built inside a massive asteroid",
            "a planet with a sentient gas species",
            "a space station orbiting a supermassive black hole",
            "a planet with a civilization that communicates through song",
            "an interstellar penal colony",
            "a planet with a biosphere made entirely of metal",
            "a research station on a planet with a binary atmosphere",
            "a space station designed to study the origin of the universe",
            "a planet with a civilization that communicates through scent",
            "a colony on a planet with an incredibly dense atmosphere",
            "a planet with a sentient rock-based species",
            "a research station orbiting a white dwarf star",
            "a planet with a biosphere that exists only in the shadows",
            "a planet with a civilization that communicates through touch",
            "a space station built inside an asteroid field",
            "a planet with a sentient energy-based species",
            "a colony on a planet with a massive hurricane always raging",
            "a planet with a biosphere made entirely of glass",
            "a research station on a planet with a highly elliptical orbit",
            "a planet with a civilization that communicates through taste",
            "a colony on a planet with a perpetually frozen surface",
            "a planet with a sentient metallic liquid species",
            "a space station designed to study the multiverse",
            "a planet with a civilization that communicates through color",
            "a colony on a planet with a biosphere that is alive",
            "a planet with a sentient species made entirely of fire",
            "a research station in a cloud of cosmic dust",
            "a planet with a civilization that communicates through vibrations",
            "a colony on a planet with an incredibly thin atmosphere",
            "a planet with a biosphere made entirely of ice",
            "a space station orbiting a massive, unexplained energy source",
            "a planet with a sentient species that can manipulate time",
            "a research station on a planet with a ring system",
            "a planet with a civilization that communicates through thought",
            "a colony on a planet with a biosphere made entirely of water",
            "a planet with a sentient species that lives in the vacuum of space",
            "a space station designed to study wormholes",
            "a planet with a civilization that communicates through taste",
            "a colony on a planet with a biosphere made entirely of fire",
            "a planet with a sentient species that feeds on radiation",
            "a research station in a nebula",
            "a planet with a civilization that communicates through light",
            "a colony on a planet with a biosphere that is telepathic",
            "a planet with a floating city made of nanobots",
            "a research station studying the properties of dark energy",
            "a colony on a planet with a superfluid atmosphere",
            "a planet with a civilization that communicates through quantum entanglement",
            "a space station orbiting a pulsar",
            "a planet with a sentient species that lives inside stars",
            "an artificial planet created by a highly advanced alien race",
            "a colony on a planet with a frozen ocean",
            "a planet with a civilization that communicates through telekinesis",
            "a research station on the edge of a black hole's event horizon",
            "a planet with a sentient species that can phase through matter",
            "a space station designed to study the creation of new universes",
            "a colony on a planet with a floating biosphere",
            "a planet with a civilization that communicates through telepathy",
            "a research station orbiting a neutron star",
            "a planet with a sentient species that exists in multiple dimensions",
            "a space station orbiting a quasar",
            "a colony on a planet with a massive underground network of caves",
            "a planet with a civilization that communicates through gravity waves",
            "a research station studying the properties of dark matter",
            "a planet with a sentient species that feeds on dark energy",
            "a space station designed to study time travel",
            "a colony on a planet with a massive tidal wave that circles the planet",
            "a planet with a civilization that communicates through radio waves",
            "a research station orbiting a red giant star",
            "a planet with a sentient species that can manipulate space-time",
            "a space station orbiting a white hole",
            "a colony on a planet with a massive crystal forest",
            "a planet with a civilization that communicates through magnetic fields",
            "a research station studying the properties of antimatter",
            "a planet with a sentient species that can travel through parallel universes",
            "a space station designed to study the properties of the Big Bang",
            "a colony on a planet with a massive storm system",
            "a planet with a civilization that communicates through sonic waves",
            "a research station orbiting a magnetar",
            "a planet with a sentient species that can communicate with other dimensions",
            "a space station orbiting a gamma-ray burst",
            "a colony on a planet with a massive underground ocean",
            "a planet with a civilization that communicates through gravitational waves",
            "a research station studying the properties of wormholes",
            "a planet with a sentient species that can travel through time",
            "a space station designed to study the properties of the multiverse",
            "a colony on a planet with a massive volcanic system",
            "a planet with a civilization that communicates through infrared radiation",
            "a research station orbiting a black dwarf star",
            "a planet with a sentient species that can teleport",
            "a space station orbiting a cosmic string",
            "a colony on a planet with a massive underground city"
        ],

        Quirk: [
            "can only wear a suit to everything",
            "literally can not add numbers",
            "has no sense of smell",
            "is a wanted war criminal",
            "is addicted to sweets, like really addicted",
            "owes money to the wrong people",
            "can only tell the truth",
            "was once buried alive",
            "constantly argues with their conscience",
            "always celebrates the end of combat with beer",
            "is afraid of pointy objects",
            "has a bad case of the blues",
            "is a loose cannon cop",
            "is never on time for anything",
            "hates to wait",
            "is convinced they are the king of all the mountains",
            "is constantly complaining that they are hungry",
            "is trying to count to infinity",
            "must plan every battle as a war general",
            "has a peg leg due to an embarrassing incident",
            "is an ex street gang member",
            "thinks they are haunted by a vengeful ghost",
            "is a kleptomaniac",
            "always must one-up the others",
            "can't hold their liquor",
            "is in a love triangle with their childhood best friends",
            "only has one facial expression",
            "is dyslexic",
            "is tone-deaf but loves to sing anyway",
            "always has to shout the name of their signature move",
            "occasionally speaks in third person",
            "constantly leaves messages in bottles",
            "is afraid of heights",
            "is completely color blind",
            "is writing an autobiography",
            "suffers from claustrophobia",
            "is addicted to collecting shiny objects",
            "must polish their weapon every night or get anxious",
            "apologizes to each one of their victims",
            "can't stand the sight of blood",
            "believes they are still in the war",
            "keeps having flashbacks to the war",
            "always has a song stuck in their head",
            "has no sense of direction",
            "constantly tries to pick up women",
            "constantly tries to pick up men",
            "always misplaces their things",
            "is a spy for their king",
            "can not keep a secret",
            "can not hold a job",
            "is a retired mid-level sports star",
            "has three identical siblings",
            "always wants to settle arguments with a duel",
            "wants to build their own castle",
            "is only here because their house burned down",
            "is a hypochondriac",
            "is afraid of women",
            "is afraid of men",
            "has an irrational fear of birds",
            "always talks like a pirate",
            "involved in the coup of a kingdom",
            "has a passion for cooking",
            "thinks they're fulfilling a prophecy",
            "can't remember anyone's name",
            "has short term memory loss",
            "must always knock first",
            "is part of the mafia",
            "is an incompetent bounty hunter",
            "has accidentally poisoned themself, twice",
            "has too many good luck charms",
            "is afraid of their own reflection",
            "gets no respect as a villain",
            "gets no respect as a hero",
            "is addicted to gambling",
            "is on the run from having an affair with a princess",
            "is a caravan robber",
            "is on their second divorce",
            "is on the run from an arranged marriage",
            "can not start the day without coffee",
            "took a vow of silence",
            "is always breaking their vow of silence",
            "owns a pet mouse",
            "likes to sing the song of their people",
            "is a very picky eater",
            "is a little off after being struck by lightning",
            "names all of their gear",
            "is working on their next masterpiece",
            "is searching for their muse",
            "has long flowing locks of hair",
            "has a beard",
            "is always wearing a hat",
            "wears the blood of their enemies",
            "does not trust anyone with their money",
            "must haggle any and every price",
            "has an imaginary friend",
            "is obsessed with proper manners",
            "is the protector of nature",
            "always asks questions later",
            "always asks questions first",
            "always believes in a fair fight",
            "never believes in a fair fight",
            "is constantly worried about their reputation",
            "seems to always break everything",
            "never misses the chance to say I told you so",
            "is oblivious to tone of voice",
            "hates getting wet",
            "hates the cold",
            "must always make a dramatic entrance",
            "has a compulsion to break windows",
            "gambled away their house",
            "swears they made a deal with a devil",
            "constantly throws their weapon",
            "carries a walking stick",
            "carries a hidden weapon in a cane",
            "carries as many knives on them as possible",
            "believes they can control the weather",
            "almost died from disease as a child",
            "always wears a hood",
            "always wears a cloak",
            "never checks for traps",
            "always triple checks for traps",
            "always has a 10 foot pole on hand",
            "was exiled for high treason",
            "was falsely accused of murder",
            "has gotten away with murder",
            "barely escaped capture by the city's law enforcement",
            "keeps a hit list",
            "has a battle plan of 'just wing it'",
            "listens at a door by breaking it down",
            "thinks locked doors should be left alone",
            "thinks an open door is an invitation",
            "is in way too deep with the wrong people",
            "searches for secret doors with a hammer",
            "has a passion for gardening",
            "is willing to try anything once",
            "is just looking for a steady job",
            "is an out of work bounty hunter",
            "is an out of work guard",
            "constantly says they know a guy",
            "never surrenders",
            "feels the need to write down everything",
            "always uses their outside voice",
            "treats every wound as life or death",
            "isn't evil, just misunderstood",
            "constantly embellishes their achievents",
            "always oversleeps",
            "likes to impersonate guards",
            "was kicked out of the church",
            "relaxes by fishing",
            "drinks away their problems",
            "has anger management issues",
            "never asks for help",
            "believes they have supernatural luck",
            "like to trick people",
            "has a slight case of amnesia",
            "knows they're in a game but nobody believes them",
            "always wants to smoke a pipe",
            "was part of a prison break",
            "helped break someone out of jail",
            "has eleven toes",
            "has to eat all the food they're given",
            "is a part time cartographer",
            "is doing this just to impress a girl",
            "is doing this just to impress a guy",
            "claims they are the king of the sea",
            "has six fingers on their right hand",
            "is seeking vengence for their murdered father",
            "is seeking vengence for their murdered mother",
            "has only nine fingers left",
            "prefers to leave no evidence",
            "always accepts a job",
            "never skips breakfast",
            "is easily surprised",
            "settles arguments with a dance off",
            "keeps a spare glove to slap with",
            "is wanted for a reward (Dead or Alive)",
            "loves nature more than people",
            "is trying to prevent forest fires",
            "was involved in an infamous heist",
            "believes trees speak to them, and only them",
            "is trying to relive their glory days",
            "likes to interrupt monologues",
            "only uses 'simple' words",
            "is constantly in disguise",
            "is easily confused",
            "tries to be optimistic about everything",
            "is pessimistic about everything",
            "is a con artist",
            "is the last member of their religion",
            "is a connoisseur of the finest wines",
            "always has a Plan B of RUN",
            "thinks they are trapped in a dream",
            "responds to insults with a duel",
            "is cursed with a year left to live",
            "has allergies that kick in at the worst times",
            "has been accused but never convicted of any crime",
            "constantly needs their fix",
            "has an arch-nemesis",
            "likes to solve problems with fire",
            "was rejected from every academy they applied to",
            "believes everything is worth overdoing",
            "is a reporter for the city newspaper",
            "is completely indecisive",
            "perfers to use words as their weapons",
            "is an active conspiracy theorist",
            "is convinced they have visions of the future",
            "is always polite about their kills",
            "wears a mask to disguise their true identity",
            "hates being interrupted",
            "is searching for a lost family heirloom",
            "tries to prepare for everything",
            "thinks traps are specifically meant for them",
            "once fell overboard on a ship",
            "was forced to walk the plank",
            "is a reformed pirate",
            "is a reformed bandit",
            "is looking for a better paying job",
            "is using the party as cover for other activities",
            "never gets rid of anything",
            "wants to map the entire world",
            "offers investigation services",
            "never remembers a face",
            "is available for hire to do dirty deeds",
            "is trying to find a cure for aging",
            "was banished from the city",
            "is on a mission from their god",
            "was once entirely frozen in ice",
            "is cursed to only ask questions",
            "is convinced that they're dreaming",
            "thinks everyone is trying to rip them off",
            "thinks light weapons are pointless",
            "thinks ranged combat is for wimps",
            "is a compulsive nail biter",
            "has a habit of interrupting others mid-conversation",
            "is an extreme neat freak",
            "has a habit of drumming their fingers on surfaces",
            "gets overly excited about things no one else cares about",
            "is a stickler for grammar and punctuation",
            "never seems to be able to make up their mind",
            "constantly checks their phone even when in the middle of a conversation",
            "has a tendency to overshare personal information",
            "is a compulsive list-maker",
            "has a habit of fidgeting",
            "is always late for appointments",
            "can never sit still for long",
            "has a tendency to talk too much",
            "is an obsessive neat freak",
            "always takes charge of group activities",
            "has a strong aversion to public speaking",
            "is prone to fits of rage",
            "has a phobia of insects",
            "is constantly cracking their knuckles",
            "is extremely forgetful",
            "has a habit of humming to themselves",
            "always needs to have the last word",
            "is a perfectionist to the extreme",
            "has a tendency to overthink everything",
            "is very competitive in all aspects of life",
            "has a habit of chewing on pencils or other objects",
            "is always early for appointments",
            "has a habit of avoiding eye contact",
            "is a compulsive liar",
            "has a tendency to be overly critical of others",
            "is always the life of the party",
            "is a bit of a germaphobe",
            "has a habit of being too blunt",
            "always has to have things done their way",
            "is constantly tapping their foot or fingers",
            "is a thrill-seeker",
            "has a habit of cracking jokes at inappropriate times",
            "is very indecisive",
            "is very emotional and wears their heart on their sleeve",
            "has a tendency to be a know-it-all",
            "is always seeking attention and validation",
            "is easily distracted and has a short attention span",
            "is a habitual procrastinator",
            "has a tendency to be a people-pleaser",
            "is extremely introverted and avoids social situations",
            "is always the first to offer help to others",
            "has a habit of apologizing excessively",
            "is always second-guessing themselves",
            "is very self-conscious and has low self-esteem",
            "is very sensitive to criticism",
            "has a tendency to be overly passive-aggressive",
            "is always trying to one-up others",
            "has a habit of exaggerating the truth",
            "is a bit of a rebel and doesn't like to follow rules",
            "has a tendency to be very argumentative",
            "is always trying to be the center of attention",
            "has a habit of talking to themselves",
            "is always looking for ways to save money",
            "is very superstitious",
            "has a tendency to be very materialistic",
            "is always willing to lend a helping hand",
            "is very straightforward and to-the-point",
            "has a habit of taking things too personally",
            "is very trusting of others",
            "is always looking for new challenges",
            "is very spiritual and in touch with their emotions",
            "has a tendency to be very passive",
            "is a bit of a hoarder",
            "has a habit of being too clingy",
            "is always on their phone",
            "is a bit of a daydreamer",
            "has a tendency to be very impulsive",
            "is always seeking new knowledge and experiences",
            "has a habit of being very sarcastic",
            "is very goal-oriented and driven",
            "is very optimistic and positive",
            "has a tendency to be very cynical"
        ]

    });

    // // Populate using a JSON file
    // // WTF.init( 'sample.json' );

    // // Populate using a Google spreadsheet ID (you must publish it first!)
    // // @see https://support.google.com/drive/answer/37579?hl=en
    // WTF.init( '2PACX-1vR8CGgeY30igIX29CrsV1E6m8vbwybFLtD7hmMuQgtNi2Jrz3Ce48flXl3QO-xbQDZpyOhIQ-JpmiQ1' );

});
